#!/bin/bash
exec 2>error1
echo "This is the start of the script"
echo "now redirecting all output to another location"
exec 1>file2
echo "This should go to the file2 file"
echo "and this should go to the error1 file" >&2
